version: '3'
services:
  nginx:
        image: nginx:1.13.7
        container_name: nginx
        depends_on:
            - flask
        volumes:
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
        ports:
            - 80:80
  flask:
    restart: always
    
    build: .
    command: python -u app.py
    ports:
      - "8080:5000"
    volumes:
      - .:/app
    networks:
            my-network:
                aliases:
                    - flask-app
    stdin_open: true
    tty: true

    
  db:
    image: mongo:latest
    hostname: test_mongodb
    environment:
      - MONGO_INITDB_DATABASE=animal_db
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=pass
    volumes:
      - ./init-db.js:/docker-entrypoint-initdb.d/init-db.js:ro
    ports:
      - 27017:27017
networks:
    my-network: